name: Deploy to DreamHost

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy_hugo_site:
    runs-on: ubuntu-latest
    name: Build and deploy Hugo site

    steps:
      # 1. Check out the code from GitHub
      - name: Check out the repo
        uses: actions/checkout@v3

      # 2. Set up the SSH agent with your private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DREAMHOST_KEY }}

      # 3. Deploy files using rsync
      - name: Deploy via rsync
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --exclude='.git/' \
            . ${{ secrets.DREAMHOST_USER }}@${{ secrets.DREAMHOST_HOST }}:${{ secrets.REMOTE_PATH }}