baseURL = 'https://castlenerda.com'
languageCode = 'en-us'
title = 'Castle Nerda'
theme = "paper"

[params]
# color style
color = 'linen'                           # linen, wheat, gray, light

# header social icons
twitter = 'CaptainNukko'               # twitter.com/YOUR_TWITTER_ID
github = 'chipheadmike'                 # github.com/YOUR_GITHUB_ID # https://bsky.app/profile/YOUR_BLUESKY_ID
rss = true                                # show rss icon

# home page profile
avatar = 'diesel.kelly@gmail.com'                 # gravatar email or image url
name = 'Mike Williams'
bio = 'Software Engineer'


# misc
disableHLJS = true                        # disable highlight.js
disablePostNavigation = true              # disable post navigation
monoDarkIcon = true                       # show monochrome dark mode icon
gravatarCdn = 'https://cdn.v2ex.com/gravatar/'         # e.g. 'https://cdn.v2ex.com/gravatar/'
math = true                               # enable KaTeX math typesetting globally
localKatex = false                        # use local KaTeX js/css instead of CDN
graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
favicon = "favicon.ico"                   # customize the default favicon
appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

# RTL supprot
direction = "rtl"                         # RTL support for Right-to-left languages