name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy_hugo_site:
    runs-on: ubuntu-latest
    name: Build and deploy Hugo site

    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.143.1'

      - name: Checkout repo on source_branch
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: '0'

      - name: Build site and push to release branch
        uses: aormsby/hugo-deploy-to-pages@v2.1
        id: build_step
        with:
          source_branch: 'main'
          release_branch: 'bon-voyage'
          hugo_publish_directory: 'public'
